name: Siddhant Jain
bio: 'Easily Distracte'
picture: 'assets/images/profile.jpg'

url: http://siddhantjain.github.io/
permalink: /:title/

#analytics: 'UA-MYANALYTICS'
#disqus: mydisqus
facebook: jainsiddhant
twitter: sichinain
linkedin: in/siddhant-jain-0b614320
youtube: myyoutube
github: siddhantjain
email: post.siddhant@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

paginate: 5
paginate_path: "blog/page:num/"

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
